Adding GitHub checks
richardguerre/flow pull request #7
Opened 2023-06-29 10:19 UTC by gitstart

CLoses out issue: [FLOW-GS-2](https://developers.gitstart.com/client/flow/ticket/FLOW-GS-2)

2023-06-29 10:49 UTC, gitstart commented
Hi @richardguerre   this pr is ready for review.

NB: The backend tests is failing and stuck in a loop . You can  create a separate ticket for that  if you would like us to fix that.

2023-06-29 13:02 UTC, richardguerre requested changes
This is a good start and I will merge it in if you just fix the server test running in an infinite loop issue.

2023-06-30 02:03 UTC, richardguerre commented
Also why was this not done as part of https://github.com/richardguerre/flow/pull/2? Can you try not to create duplicate PRs?

2023-06-30 11:54 UTC, udochukwu commented on .github/actions/setup/action.yml
> +    required: true
Yeah. It's not needed. We'll remove it.

2023-06-30 12:03 UTC, udochukwu commented on .github/workflows/checks.yml
> +        uses: ./.github/actions/setup
Yes. It's required in the 2 files, else the flow wont run.

2023-07-17 03:01 UTC, richardguerre commented on .github/workflows/checks.yml
> +
```suggestion
    env:
      DATABASE_URL: postgresql://postgres@localhost:5432/flow
      CI: true

```

2023-07-17 03:02 UTC, richardguerre commented on .github/actions/setup/action.yml
> +        node-version: "18.13.0"
```suggestion
        node-version: "18.12.1"
```

2023-07-17 03:03 UTC, richardguerre commented on .github/actions/setup/action.yml
> +    required: true
```suggestion
description: "Sets up environment"
```

2023-07-17 03:34 UTC, richardguerre commented on .github/workflows/checks.yml
> +      CI: true
```suggestion
    env:
      CI: true
      DATABASE_URL: postgresql://postgres@localhost:5432/flow
      ORIGIN: http://localhost:4000
```

2023-07-18 03:39 UTC, richardguerre commented on .github/workflows/checks.yml
> +        run: npm run test -w apps/server
```suggestion
        run: npm run test -w apps/server -- test/utils/pluralize.test.ts
```

2023-07-18 03:50 UTC, richardguerre commented on .github/workflows/checks.yml
> +        run: npm run gen -w apps/server
```suggestion
      - name: Run DB migrations
        run: npm run db:dev
```

2023-07-18 03:51 UTC, richardguerre commented on .github/workflows/checks.yml
> +        run: npm run test -w apps/server -- test/utils/pluralize.test.ts
```suggestion
      - name: Test check
        run: npm run test -w apps/server -- test/graphql/Item.test.ts
```

2023-07-18 03:58 UTC, richardguerre commented on .github/workflows/checks.yml
> +        run: npm run db:dev
```suggestion
        run: DATABASE_URL=postgres://postgres:postgres@localhost:5432/flow_test npm run db:dev
```

2023-07-18 04:00 UTC, richardguerre commented on .github/workflows/checks.yml
> +      DATABASE_URL: postgresql://postgres@localhost:5432/flow
```suggestion
      DATABASE_URL: postgresql://postgres@localhost:5432/flow # `flow` will get replaced with `flow_test` (see .vitest/prisma.ts) as `flow` is the local development DB and `flow_test` is the test DB.
```

2023-07-18 04:04 UTC, richardguerre commented on .github/workflows/checks.yml
> +          POSTGRES_PASSWORD: pg
```suggestion
          POSTGRES_PASSWORD: postgres
```

2023-07-18 04:18 UTC, richardguerre commented on .github/workflows/checks.yml
> +        run: npm run test -w apps/server -- test/graphql/Item.test.ts
```suggestion
  # server-test:
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: flow_test
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432

  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   env:
  #     CI: true
  #     NODE_ENV: test
  #     DATABASE_URL: postgresql://postgres@localhost:5432/flow # `flow` will get replaced with `flow_test` (see .vitest/prisma.ts) as `flow` is the local development DB and `flow_test` is the test DB.
  #     ORIGIN: http://localhost:4000

  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: Setup environment (node, npm install)
  #       uses: ./.github/actions/setup
  #     - name: Run DB migrations
  #       run: DATABASE_URL=postgres://postgres:postgres@localhost:5432/flow_test npm run db:dev
  #     - name: Test check
  #       run: npm run test -w apps/server -- test/graphql/Item.test.ts
```

2023-07-18 04:19 UTC, richardguerre commented on .github/workflows/checks.yml
> +name: CI/CD Checks
```suggestion
name: CI
```

2023-07-18 04:20 UTC, richardguerre commented on .github/workflows/checks.yml
> +      - name: Test check
```suggestion
      - name: Run tests
```

2023-07-18 04:26 UTC, merged